site_name: Tech Blogs
site_description: A Tech Blog on Azure Cloud
site_url: https://sitename.example
theme:
  name: material
  palette:
    # Dark mode palette
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
      primary: deep orange
      accent: deep purple
    # Light mode palette
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: blue
      accent: deep purple

plugins:
  - search
  - blog:
      blog_dir: .
      archive_date_format: yyyy
      archive_url_date_format: yyyy
      categories_allowed:
        - Tech
        - Life
      post_url_format: "{slug}"

  - tags:
      tags_file: tags.md

extra:
  social:
    - icon: simple/youtube
      link: https://www.youtube.com/@rushikeshdeshmukh9507
    - icon: fontawesome/brands/github-alt
      link: https://github.com/rushikeshdeshmukh2025
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rushi-deshmukh/

hooks:
  - hooks/socialmedia.py

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg