authors:
  rushikesh:
    name: Rushikesh Deshmukh
    email: rushi.deshmukh@live.com
    description: Azure Cloud Architect
    url: https://rushikeshdeshmukh2025.github.io/mk-docks/
    avatar: https://rushikeshdeshmukh2025.github.io/mk-docks/assets/logo.png

  team:
    name: Tech Blogs Team
    description: A team of tech enthusiasts
    url: https://techblogs.example
    avatar: https://github.com/rushikeshdeshmukh2025/mk-docks/blob/main/docs/assets/logo.png